name: Deployment Pipeline
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - run: echo Hello

  QA:
    runs-on: self-hosted
    needs:
      - DEV
    steps:
      - run: echo Hello

  UAT:
    runs-on: self-hosted
    needs:
      - QA
    steps:
      - run: echo Hello

  PROD:
    runs-on: self-hosted
    needs:
      - UAT
    steps:
      - run: echo Hello

